version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dev"
    container_name: "dev"
    volumes:
      - ./postgres:/var/lib/postgresql/data